[gcp]
service_account_json = """
{
  "type": "service_account",
  "project_id": "pdf-tool-logs",
  "private_key_id": "c312c4041ead7955e25b0cef22f60197e716cb89",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0B...\n-----END PRIVATE KEY-----\n",
  "client_email": "website@pdf-tool-logs.iam.gserviceaccount.com",
  "client_id": "100722900645678047",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/website%40pdf-tool-logs.iam.gserviceaccount.com"
}
"""

